🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/setup_rvm b/bin/setup_rvm
--- a/bin/setup_rvm
+++ b/bin/setup_rvm
@@ -1,77 +1,84 @@
 #!/usr/bin/env bash
-
-APPNAME="$(basename $0)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="install_rvm"
 USER="${SUDO_USER:-${USER}}"
-export PATH="$HOME/.local/share/rvm/bin:$PATH"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : install_rvm
-# @Created     : Wed, Aug 05, 2020, 02:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Ruby Version Manager installer
-#
+##@Version       : 031520211551-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : install_rvm --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Monday, Mar 15, 2021 15:51 EDT
+# @File          : install_rvm
+# @Description   : Ruby Version Manager installer
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-# Set functions
-
-SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
-SCRIPTSFUNCTDIR="${SCRIPTSAPPFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-applications.bash}"
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if [ -f "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE"
-elif [ -f "$HOME/.local/share/CasjaysDev/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$HOME/.local/share/CasjaysDev/functions/$SCRIPTSFUNCTFILE"
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
 else
-  curl -LSs "$SCRIPTSFUNCTURL/$SCRIPTSFUNCTFILE" -o "/tmp/$SCRIPTSFUNCTFILE" || exit 1
-  . "/tmp/$SCRIPTSFUNCTFILE"
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
 fi
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Set options
-[[ -f "$HOME/.local/share/rvm/scripts/rvm" ]] && source "$HOME/.local/share/rvm/scripts/rvm"
-
+# helper function
+__version() { app_version; }
+__help() {
+  app_help "Usage: install_rvm  -  install_rvm --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-# main program
-
-if [ -n "$(command -v rvm)" ]; then
-  printf_green "RVM is already installed"
-else
-  printf_green "installing RVM!"
-  if [ "$1" = "--system" ]; then
-    if [[ "$USER" != root ]]; then
-      printf_red "Please re-run this script with sudo"
-      exit
-    fi
-    sudo -H gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB >/dev/null 2>&1 &&
-      sudo -H curl -LSsq https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer >/tmp/rvm_install &&
-      sudo -H chmod 755 /tmp/rvm_install &&
-      sudo -H bash /tmp/rvm_install master --version latest --path /usr/local/share/rvm --ignore-dotfiles --ruby --rails >/dev/null 2>&1 &&
-      [[ -f /usr/local/share/rvm/scripts/rvm ]] && sudo -H -s source /usr/local/share/rvm/scripts/rvm &&
-      sudo -H rm -Rf /tmp/rvm_install &&
-      devnull sudo -H rvm autolibs enable &&
-      devnull sudo -H rvm install "ruby-2.7.1" --auto-dotfiles &&
-      devnull sudo -H rvm use "ruby-2.7.1" --default --create &&
-      printf_green "Finished installing RVM!" || printf_exit "Installation failed"
+# Main function
+main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash curl git || exit 1
+  am_i_online --error || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  local RVMPATH="$HOME/.local/share/rvm"
+  export PATH="$RVMPATH/bin:$PATH"
+  [[ -f "$RVMPATH/scripts/rvm" ]] && source "$RVMPATH/scripts/rvm"
+  if [ -n "$(command -v rvm)" ]; then
+    printf_green "RVM is already installed"
   else
+    printf_green "installing RVM!"
     gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB >/dev/null 2>&1 &&
-      curl -LSsq https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer >/tmp/rvm_install &&
-      chmod 755 /tmp/rvm_install &&
-      bash /tmp/rvm_install master --version latest --path "$HOME/.local/share/rvm/scripts/rvm" --ignore-dotfiles --ruby --rails >/dev/null 2>&1 &&
-      [[ -f "$HOME/.local/share/rvm/scripts/rvm" ]] && source "$HOME/.local/share/rvm/scripts/rvm" &&
-      devnull rvm autolibs enable &&
-      devnull rvm install "ruby-2.7.1" --auto-dotfiles &&
-      devnull rvm use "ruby-2.7.1" --default --create &&
-      printf_green "Finished installing RVM!" || printf_exit "Installation failed"
-  fi
-fi
-
+    curl -LSsq https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer >/tmp/rvm_install &&
+    chmod 755 /tmp/rvm_install &&
+    bash /tmp/rvm_install master --version latest --path "$RVMPATH/scripts/rvm" --ignore-dotfiles --ruby --rails >/dev/null 2>&1 &&
+    [[ -f "$RVMPATH/scripts/rvm" ]] && source "$RVMPATH/scripts/rvm" &&
+    devnull rvm autolibs enable &&
+    devnull rvm install "ruby-2.7.1" --auto-dotfiles &&
+    devnull rvm use "ruby-2.7.1" --default --create &&
+    printf_green "Finished installing rVM!" || printf_exit "Installation failed"
+    fi
+  return "${exitCode:-$?}"
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
+
